; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32@ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	earlephilhower/ESP8266Audio@^2.0.0
	xylopyrographer/LiteLED@^1.2.0
	bodmer/TFT_eSPI@^2.5.43
	lvgl/lvgl@^9.2.2
board_build.f_cpu = 80000000L
board_build.f_flash = 80000000L
upload_speed = 921600
build_flags = -DTASK_STACK_SIZE=102400
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=1
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
